seed: # seed to recreate results
corpora: # dataset name or a list from the following datasets [ksuemotions, ravess, crema, tess, savee]
data_path: # dataset path

model_name_or_path: # underlying pretrained model name or path
pooling_mode: mean
attention_mask: # null/ False or True

output_dir: # model output directory. EXAMPLE ./content/models/new_model_name

test_corpora: null
test_corpora_path: null
