seed: # seed to recreate results
corpora: # dataset name or a list from the following datasets [ksuemotions, ravess, crema, tess, savee]
data_path: # dataset path

model_name_or_path: # underlying pretrained model name or path
pooling_mode: mean
attention_mask: # null/ False or True

output_dir: # model output directory. EXAMPLE ./content/models/new_model_name

# XX  # Split files wil be output into <output_dir>/splits/<split>.csv
# test: # test split file path EXAMPLE ./content/models/new_model_name/splits/test.csv
# train: # train split file path (train.csv)
# evaluate: # vaildation split file path (valid.csv)
