seed: # seed to recreate results

corpora: # dataset name or a list from the following datasets ['ksuemotions', 'ravdess', 'crema', 'tess', 'savee', 'aesdd'] jlcorpus, iemocap
data_path: # dataset path

processor_name_or_path: # underlying pretrained model name or path
pooling_mode: # pooling method: 'mean', 'sum', or 'max'
return_attention_mask: False # True for models built with an attention_mask
freeze_feature_extractor:  # True or False


output_dir: # model output directory. EXAMPLE './content/models/model_name'
cache_dir: null # Optional: cach directory
checkpoint: # path to model's checkpoint

# Optional: if planning to test the model on a different dataset. Will only be used when running evaluate.py directly.
test_corpora: null
test_corpora_path: null
