seed: 101

corpora: ksuemotions
data_path: ./content/data/ksu_emotions/data/SPEECH/ # /scratch/jia2025/w2v2_xlsr_arabic_ser/content/data/ksu_emotions # /Users/jia2025/Documents/GitHub Clones/audio_processing/Emotion_recognition_Wav2Vec2/content/data/ksu_emotions

processor_name_or_path: elgeish/wav2vec2-large-xlsr-53-arabic
pooling_mode: mean
return_attention_mask: False  # False for elgeish/wav2vec2-large-xlsr-53-arabic
freeze_feature_extractor: True

# Training Arguments
output_dir: ./content/models/wav2vec2-xlsr-arabic-ksuemotions-no-freeze
num_train_epochs: 1.0
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 2
evaluation_strategy: steps
fp16: True
save_steps: 10
eval_steps: 10
logging_steps: 10
learning_rate: 1e-4
save_total_limit: 2

cache_dir: ./content/cache
checkpoint: /checkpoint-320

# Optional: if planning to test the model on a different dataset
test_corpora: null # ravdess
test_corpora_path: null # /Users/jia2025/Documents/GitHub Clones/audio_processing/Emotion_recognition_Wav2Vec2/content/data/kaggle/input/ravdess-emotional-speech-audio
