seed: 101

corpora: ksuemotions
data_path: ./content/data/ksu_emotions/data/SPEECH/

processor_name_or_path: facebook/wav2vec2-base
pooling_mode: mean
return_attention_mask: False
freeze_feature_extractor: False

output_dir: ./content/models/wav2vec2-arabic-ksuemotions-finetuned
cache_dir: ./content/cache
checkpoint: /checkpoint-320

# Optional: if planning to test the model on a different dataset
test_corpora: null
test_corpora_path: null
