seed: 101

corpora: ksuemotions
data_path: ./content/data/ksu_emotions/data/SPEECH/

processor_name_or_path: AndrewMcDowell/wav2vec2-xls-r-1b-arabic
pooling_mode: mean
return_attention_mask: True
freeze_feature_extractor: True

# Training Arguments
output_dir: ./content/models/wav2vec2-xls-r-1b-arabic-ksuemotions-frozen
num_train_epochs: 3.0
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 8
evaluation_strategy: steps
fp16: True
save_steps: 10
eval_steps: 10
logging_steps: 10
learning_rate: 1e-4
save_total_limit: 2
report_to: 'wandb'
# gradient_checkpointing: True

cache_dir: ./content/cache
checkpoint: /checkpoint-980
resume_from_checkpoint: False #./content/models/wav2vec2-xls-r-1b-arabic-ksuemotions-frozen/checkpoint-10

# Optional: if planning to test the model on a different dataset
test_corpora: null
test_corpora_path: null
