seed: 101

corpora: ['ravdess', 'crema', 'tess', 'savee']
data_path: [ "./content/data/kaggle/input/ravdess-emotional-speech-audio/audio_speech_actors_01-24/",
  "./content/data/kaggle/input/cremad/AudioWAV/",
  "./content/data/kaggle/input/toronto-emotional-speech-set-tess/tess toronto emotional speech set data/TESS Toronto emotional speech set data/",
  "./content/data/kaggle/input/surrey-audiovisual-expressed-emotion-savee/ALL/"
  ]

processor_name_or_path: jonatasgrosman/wav2vec2-large-xlsr-53-english
pooling_mode: mean
return_attention_mask: True

output_dir: ./content/models/wav2vec2-xlsr-english-ravdess-crema-tess-savee
cache_dir: ./content/cache

# Optional: if planning to test the model on a different dataset
test_corpora: null
test_corpora_path: null
