seed: 101

corpora: ravdess
data_path: ./content/data/kaggle/input/ravdess-emotional-speech-audio/audio_speech_actors_01-24/

processor_name_or_path: elgeish/wav2vec2-large-xlsr-53-arabic
pooling_mode: mean
return_attention_mask: False  # False for elgeish/wav2vec2-large-xlsr-53-arabic
freeze_feature_extractor: True

# Training Arguments
output_dir: ./content/models/wav2vec2-xlsr-53-arabic-ravdess-frozen
num_train_epochs: 3.0
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 2
evaluation_strategy: steps
fp16: True
save_steps: 10
eval_steps: 10
logging_steps: 10
learning_rate: 1e-4
save_total_limit: 2

cache_dir: ./content/cache
checkpoint: /checkpoint-430
resume_from_checkpoint: True

# Optional: if planning to test the model on a different dataset
test_corpora:  # aesdd
test_corpora_path:  # ./content/data/aesdd/
