seed: 101

corpora: ksuemotions
data_path: ./content/data/ksu_emotions/data/SPEECH/

processor_name_or_path: elgeish/wav2vec2-large-xlsr-53-arabic
pooling_mode: mean
return_attention_mask: False  # False for elgeish/wav2vec2-large-xlsr-53-arabic

output_dir: ./content/models/wav2vec2-xlsr-arabic-ksuemotions

# Optional: if planning to test the model on a different dataset
test_corpora: null
test_corpora_path: null
