seed: 101

corpora: aesdd
data_path: ./content/data/aesdd/

processor_name_or_path: m3hrdadfi/wav2vec2-xlsr-greek-speech-emotion-recognition
pooling_mode: mean
return_attention_mask: True
freeze_feature_extractor: True

output_dir: ./content/models/wav2vec2-xlsr-greek-aesdd-frozen
cache_dir: ./content/cache
checkpoint: /checkpoint-320

# Optional: if planning to test the model on a different dataset
test_corpora: ksuemotions
test_corpora_path: ./content/data/ksu_emotions/data/SPEECH/
