seed: 101

corpora: ['ravdess', 'crema', 'tess', 'savee']
data_path: [ "./content/data/kaggle/input/ravdess-emotional-speech-audio/audio_speech_actors_01-24/",
  "./content/data/kaggle/input/cremad/AudioWAV/",
  "./content/data/kaggle/input/toronto-emotional-speech-set-tess/tess toronto emotional speech set data/TESS Toronto emotional speech set data/",
  "./content/data/kaggle/input/surrey-audiovisual-expressed-emotion-savee/ALL/"
  ]

processor_name_or_path: jonatasgrosman/wav2vec2-large-xlsr-53-english
pooling_mode: mean
return_attention_mask: True
freeze_feature_extractor: True

# Training Arguments
output_dir: ./content/models/wav2vec2-xlsr-english-ravdess-crema-tess-savee-frozen
num_train_epochs: 1.0
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 2
evaluation_strategy: steps
fp16: True
save_steps: 10
eval_steps: 10
logging_steps: 10
learning_rate: 1e-4
save_total_limit: 2

cache_dir: ./content/cache
checkpoint: /checkpoint-1200
resume_from_checkpoint: False

# Optional: if planning to test the model on a different dataset
test_corpora: ksuemotions
test_corpora_path: ./content/data/ksu_emotions/data/SPEECH/
