seed: 101

corpora: AESDD
data_path: ./content/data/aesdd

processor_name_or_path: m3hrdadfi/wav2vec2-xlsr-greek-speech-emotion-recognition
pooling_mode: mean
return_attention_mask: True  

output_dir: ./content/models/wav2vec2-xlsr-greek-aesdd

# Optional: if planning to test the model on a different dataset
test_corpora: null
test_corpora_path: null
