seed: 101

corpora: ksuemotions
data_path: ./content/data/ksu_emotions/data/SPEECH/

processor_name_or_path: lighteternal/wav2vec2-large-xlsr-53-greek
pooling_mode: mean
return_attention_mask: False
freeze_feature_extractor: True

# Training Arguments
output_dir: ./content/models/wav2vec2-xlsr-53-greek-ksuemotions-frozen
num_train_epochs: 5.0
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 2
evaluation_strategy: steps
fp16: True
save_steps: 10
eval_steps: 10
logging_steps: 10
learning_rate: 1e-4
save_total_limit: 2

cache_dir: ./content/cache
checkpoint: /checkpoint-1640
resume_from_checkpoint: False

# Optional: if planning to test the model on a different dataset
test_corpora:  # aesdd
test_corpora_path:  #./content/data/aesdd/
